# Generated by Django 4.0.6 on 2022-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_personal_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='fecha_service',
            field=models.DateTimeField(null=b'I01\n'),
        ),
    ]
